# Default values for ajobot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/ass-a-service/ajobot
  pullPolicy: IfNotPresent
  tag: "v6.4.0"

imagePullSecrets: []

botToken: changeme
# debug: 1 # enable this for admin commands, usually used for test environments
# sentryDsn: https://xxxxxxx
# redisHost: # enable this if you want to set your own redis host, if you dont set any we will set the default one

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 60Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  enabled: true
  image:
    repository: redislabs/redistimeseries
    tag: 1.6.10
  architecture: standalone
  auth:
    enabled: false
  master:
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 150Mi
        cpu: 100m
    persistence:
        enabled: false
  commonConfiguration: |-
    appendonly yes
    save ""
    aof-use-rdb-preamble yes  
    loadmodule /usr/lib/redis/modules/redistimeseries.so
