apiVersion: v1
data:
  {{- if .Values.redisHost}}
  REDIS_HOST: {{ .Values.redisHost }}
  {{- else }}
  REDIS_HOST: {{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local
  {{- end }}
  {{- if .Values.botToken}}
  TOKEN: {{ .Values.botToken }}
  {{- end }}
  {{- if .Values.debug}}
  DEBUG: {{ .Values.debug | quote }}
  {{- end }}
  {{- if .Values.sentryDsn}}
  SENTRY_DSN: {{ .Values.sentryDsn }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}

