apiVersion: v1
data:
  REDIS_HOST: {{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local
  {{- if .Values.botToken}}
  TOKEN: {{ .Values.botToken }}
  {{- end }}
  {{- if .Values.debug}}
  DEBUG: {{ .Values.debug }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}

